colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: FatBoyRim
layout_spectrum: 0.3974384390749037
typography_spectrum: 0.9165184206794947
color:
  brandStrength: 0.6747720611747354
  lightness: 0.15531102288514376
  saturation: 0.3159541580826044
  rhythmicContrast: 0.5939451633021235
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a9ec08b-1da2-48b7-90ed-577577aaf213.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/3a9ec08b-1da2-48b7-90ed-577577aaf213.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Fat Boy Rim
description: ''
github: true
content_rating:
  adult: false
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/630b7906-eb0b-43cc-8495-78ce4af778c3.png
